name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call: {}

jobs:
  precommit:
    runs-on: uhg-runner
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Get Artifactory Access Token
        id: setup-jfrog-saas
        uses: uhg-pipelines/epl-jf/saas-setup@1152b773c8d4b55c0bb5b2a15c82981fe0b3db35 # v5.4
        with:
          pip-setup: true
      - name: Checkout prek
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          repository: j178/prek-action
          ref: 4e14d07f9231acabce116ccfca13b13dd9755ece  # v3.0.0
          path: .github/actions/prek
      - name: Run pre-commit
        uses: ./.github/actions/prek
