name: SARIF files

on:
  push:
    branches: [trunk]
  pull_request:
    branches: ['**']
  workflow_call: {}

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  zizmor:
    name: zizmor via PyPI
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required for upload-sarif to upload SARIF files.
      contents: read # Needed to clone the repo.
      actions: read # Needed for upload-sarif to read workflow run info.
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Generate SARIF files
        uses: j178/prek-action@4e14d07f9231acabce116ccfca13b13dd9755ece  # v3.0.0
        with:
          extra-args: --color=always --all-files ruff-sarif zizmor-sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@4e94bd11f71e507f7f87df81788dff88d1dacbfb # v4.31.0
        with:
          sarif_file: ruff.sarif
          category: ruff

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@4e94bd11f71e507f7f87df81788dff88d1dacbfb # v4.31.0
        with:
          sarif_file: zizmor.sarif
          category: zizmor
